#+AUTHOR:     
#+TITLE:      
#+OPTIONS:     toc:nil num:nil 
#+LATEX_HEADER: \usepackage{mathrsfs}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{dcolumn}
#+LATEX_HEADER: \usepackage{subfigure}
#+LATEX_HEADER: \usepackage{coffee}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \RequirePackage{fancyvrb}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small,formatcom = {\color[rgb]{0.1,0.2,0.9}}}
#+LATEX: \newcommand{\ep}{{\bf e}^\prime}
#+LATEX: \setlength{\parindent}{0in}
#+LATEX: \renewcommand{\email}[1]{\textcolor{blue}{\texttt{#1}}}
#+LATEX: \renewcommand{\cd}{$\circ$ }
#+STARTUP: fninline

*Econometrics: Multiple Equation Estimation* \hfill
*ARE212*: Section Syllabus \\ \hline \\
\vspace{10pt}
\begin{tabular}{ l l }
 {\bf Professor}     &  Max Auffhammer                   \\
 {\bf GSI}           &  Dan Hammer                       \\
 {\bf Section time}       &  Fridays, 11:00AM-12:00PM  \\
 {\bf Section location}   &  285 CORY  \\
 {\bf e-mail}        &  \email{danhammer@berkeley.edu}  \\
 {\bf twitter}       &  \texttt{@econohammer}  \\
 {\bf github}       &  \texttt{@danhammer}  
\end{tabular}
\vspace{10pt}
\hline

\bigskip 


The purpose of this document is to outline the sections for Max
Auffhammer's econometrics course, the first semester of the ARE
econometrics sequence.  The purpose of these sections is to introduce
=R= for econometrics, illustrating the theory presented in class with
applied examples.  Actual data work.  \\

This is my first attempt as a graduate student instructor, so be
gentle.  I tell you this to warn you that the section notes might
change throughout the course, not to reveal my weaknesses --- of which
I have none.  The outline of sections below is based on the
progression from previous years.  The outline might change, but the
final section notes will always be posted on Blackboard at least one
week in advance of class. The development version of the notes and =R=
code will be posted to my Github respository: \\

\\ \\ \email{www.github.com/danhammer/ARE212} \\ 

Here, you will be able to see the evolution of the notes, as well as
the structure and protocol associated with production code.  If you
want to collaborate on the notes, join Github and send me an e-mail.
I will help get you started, if needed.[fn:: A side note: I have
reserved the handle =auffhammer=, just in case Max ever wants to join.
I will try dearly to extract the rents associated with absolute
scarcity.  He claims he'll just get another handle; but this is not a
credible threat, since =auffhammer= is an awesome Github handle.]

\vspace{10pt}
\begin{tabular}{ l l }
 {\bf January 18}        &  Matrix operations in \texttt{R}        \\ \\
 {\bf January 25}        &  OLS regression from first principles   \\ \\
 {\bf February 2}        &  Goodness of fit                        \\ \\
 {\bf Februray 9}        &  Hypothesis testing                     \\ \\
 {\bf February 16}       &  Efficiency of GLS                      \\ \\
 {\bf February 23}       &  Instrumental variables                      
\end{tabular}
\vspace{10pt}

The =R= code for each section is posted on the Github site, and should
run on any machine and any operating system.  Please feel free to
e-mail me with any questions.  \\

*Office hours*: I don't really use my office on campus.  In fact, I'm
 not even sure where it is.  Please e-mail me with questions!  I'll
 respond promptly, over e-mail or in person.\\

*Homework*: Problem sets will be collected at the end of class on the
 specified date.  Ultimately, Max will decide the deductions for late
 homework.  I will not stray from his stated policies.\\

*Grading*: The problem sets will be graded on a 100 point scale.
 Partial credit will be awarded for partial answers.  I will do my
 best to award partial credit fairly, compensating both effort and
 accuracy.  The problem set grades don't really matter too much,
 though, so I can't imagine anyone will take issue with the grades.\\

*Attendance*: You are not required to come.  I hope the sections are
 helpful, but I carry no conception that the sections will be
 uniformly helpful.  Only come if the sections are helpful to you.\\

*Quizzes*: There are no quizzes.  But I scared you, didn't I? \\

*Additional resources*: There are many online, free resources to learn
 =R= and basic econometrics; and there even exist resources that do
 both at once.  I have listed a few helpful resources for both writing
 code and scripting econometric routines.  

1. *Econometrics in R*, \email{cran.r-project.org/doc/contrib/Farnsworth-EconometricsInR.pdf}

2. *R Style Guide*, \email{google-styleguide.googlecode.com/svn/trunk/google-r-style.html}

3. *Econometrics*, /Bruce Hansen/, \email{www.ssc.wisc.edu/\char`\~ bhansen/econometrics/Econometrics.pdf}

*Academic integrity*: /This is cribbed directly from the UC Berkeley
 site/: These are some basic expectations of students with regards to
 academic integrity: \cd Any work submitted should be your own
 individual thoughts, and should not have been submitted for credit in
 another course unless you have prior written permission to re-use it
 in this course from this instructor. \cd All assignments must use
 "proper attribution," meaning that you have identified the original
 source and extent or words or ideas that you reproduce or use in your
 assignment. This includes drafts and homework assignments!  \cd If
 you are unclear about expectations, ask your instructor or GSI.  \cd
 Do not collaborate or work with other students on assignments or
 projects unless you have been given permission or instruction to do
 so.
