#+AUTHOR:     
#+TITLE:      
#+OPTIONS:     toc:nil num:nil 
#+LATEX_HEADER: \usepackage{mathrsfs}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{coffee}
#+LATEX_HEADER: \usepackage{dcolumn}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{subfigure}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \RequirePackage{fancyvrb}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small,formatcom = {\color[rgb]{0.1,0.2,0.9}}}
#+LATEX: \newcommand{\ep}{{\bf e}^\prime}
#+LATEX: \setlength{\parindent}{0in}
#+LATEX: \renewcommand{\email}[1]{\textcolor{blue}{\texttt{#1}}}
#+LATEX: \renewcommand{\cd}{$\circ$ }
#+STARTUP: fninline

*Econometrics: Multiple Equation Estimation* \hfill
*ARE212*: Section Syllabus \\ \hline \\
\vspace{10pt}
\begin{tabular}{ l l }
 {\bf Professor}             &  Max Auffhammer                  \\
 {\bf GSI}                   &  Dan Hammer                      \\
 {\bf Section time}          &  Fridays, 11:00AM-12:00PM        \\
 {\bf Section location}      &  285 CORY                        
 \end{tabular}
\hfill
\begin{tabular}{ l l }
 {\bf Office hours}          &  Wednesdays, 4:00PM-5:00PM         \\
 {\bf OH location}           &  234 GIANNINI                    \\
 {\bf e-mail}                &  \href{mailto:danhammer@berkeley.edu} {\email{danhammer@berkeley.edu}}  \\
 {\bf twitter}               &  \href{www.twitter.com/econohammer}{\email{@econohammer}}            \\
\end{tabular}
\vspace{10pt}
\hline

\bigskip 

\coffee{1}

The purpose of this document is to outline the sections for Max
Auffhammer's econometrics course, the first semester of the ARE
econometrics sequence.  The objective of the sections is to introduce
=R= for econometrics, illustrating the lecture notes with applied,
coded examples. Actual data work.  \\

The outline of sections below is based on the progression from
previous years.  The outline might change, but the final section notes
will always be posted on bSpace at least one week in advance of
section. The development version of the notes and =R= code will be
posted to my Github respository: \\

\\ \\ [[www.github.com/danhammer/ARE212][\email{github.com/danhammer/ARE212}]] \\

You do not need to know anything about Github to productively and
successfully engage in section.  But you will be able to see the
evolution of the notes, as well as the structure and protocol
associated with production code.  If you want to collaborate on the
notes, join Github and send me an e-mail.  I will help get you
started, if needed.[fn:: A side note: I have reserved the handle
=auffhammer=, just in case Max ever wants to join.  I will try dearly
to extract the rents associated with absolute scarcity.  He claims
he'll just get another handle; but this is not a credible threat,
since =auffhammer= is an awesome Github handle.]

\vspace{10pt}
\begin{tabular}{ l l }
 {\bf February 1}        &  Preliminaries and setup                  \vspace{4pt} \\ 
 {\bf February 8}        &  Matrix operations in \texttt{R}          \vspace{4pt} \\ 
 {\bf February 15}       &  OLS regression from first principles     \vspace{4pt} \\ 
 {\bf Februray 22}       &  Goodness of fit                          \vspace{4pt} \\ 
 {\bf March 1}           &  Hypothesis testing                       \vspace{4pt} \\ 
 {\bf March 8}           &  Returns to education, empirical example  \vspace{4pt} \\ 
 {\bf March 15}          &  Efficiency of GLS                        \vspace{4pt} \\ 
 {\bf March 22}          &  Large sample properties of OLS           \vspace{4pt} \\ 
 {\bf April 5}           &  Testing for heteroskedasticity           \vspace{4pt} \\ 
 {\bf April 12}          &  Feasible generalized least squares       \vspace{4pt} \\ 
 {\bf April 19}          &  Serial correlation                       \vspace{4pt} \\ 
 {\bf April 26}          &  Instrumental variables                   \vspace{4pt} \\ 
 {\bf May 3}             &  Spatial analysis in \texttt{R}           
\end{tabular}
\vspace{10pt}

The =R= code for each section will be posted on both bSpace and
Github, and should run on any machine and any operating system.
Please feel free to e-mail me with any questions.  \\

*Office hours*: I don't use my office on campus.  In fact, I'm not
 even sure where it is. Instead, I'll be in 204 Giannini from 4:00pm -
 5:00pm on Tuesdays.  If you can't make regular office hours, please
 e-mail me with questions!  I'll respond promptly, over e-mail or in
 person within 48 hours.  If I can't answer in less than a paragraph,
 I'll ask you to come to office hours.  I will not hold office hours
 on Tuesday, March 19 as I will be at an out-of-town conference.\\

*Homework*: Problem sets will be collected at the end of class on the
 specified date.  Ultimately, Max will decide the deductions for late
 homework.  I will not stray from his stated policies.\\

*Grading*: The problem sets will be graded on a 100 point scale.  A
 face-plant fail or no-show will be assigned a 0; a
 tried-and-came-close will be assigned a 70; and a good-showing will
 be assigned a 100.  \\

*Attendance*: You are not required to come.  I hope the sections are
 helpful, but I carry no conception that the sections will be
 uniformly helpful.  Only come if the sections are helpful to you.\\

*Quizzes*: There are no quizzes.  But I scared you, didn't I? \\

*Additional resources*: There are many online, free resources to learn
 =R= and basic econometrics; and there even exist resources that do
 both at once.  I have listed a few helpful resources for both writing
 code and scripting econometric routines.  

1. *Econometrics in R*,
   \email{cran.r-project.org/doc/contrib/Farnsworth-EconometricsInR.pdf}

2. *R Style Guide*,
   \email{google-styleguide.googlecode.com/svn/trunk/google-r-style.html}

3. *Econometrics*, /Bruce Hansen/, \email{www.ssc.wisc.edu/\char`\~
   bhansen/econometrics/Econometrics.pdf}

*Academic integrity*: /This is cribbed directly from the UC Berkeley
 site/: These are some basic expectations of students with regards to
 academic integrity: \cd Any work submitted should be your own
 individual thoughts, and should not have been submitted for credit in
 another course unless you have prior written permission to re-use it
 in this course from this instructor. \cd All assignments must use
 "proper attribution," meaning that you have identified the original
 source and extent or words or ideas that you reproduce or use in your
 assignment. This includes drafts and homework assignments!  \cd If
 you are unclear about expectations, ask your instructor or GSI.  \cd
 Do not collaborate or work with other students on assignments or
 projects unless you have been given permission or instruction to do
 so.
